language: generic
sudo: required
services:
  - docker # Generally needed

# TAG can be anything (used inside docker. MYTAG also works)
before_install:
  - docker build -t dbeken85/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dbeken85/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-153741691820"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
